### ISSUE TITLE
Missing '<type>_of_string'-like functions implementation

### ISSUE THREAD

**Issue by lvjonok** [geoffder/clipper2c#2]
Good day!

I have found that some methods like

```c
ClipperPath64 *clipper_path64_of_string(void *mem, char *str);
ClipperPathD *clipper_pathd_of_string(void *mem, char *str);
```

from `clipper2c.h` are missing their implementation. After quick search I did not find them in original **Clipper2** library. Should they be deleted, or you would like to add them later?

Maybe you could take implementation from [here](https://github.com/AngusJohnson/Clipper2/blob/main/CPP/Utils/ClipFileLoad.cpp), this file contains implementation of loading path from string.

**Comment by geoffder** [comment]
Oh good catch, those corresponded to the `MakePath` constructors, but they have recently been dropped from the top level interface of Clipper2. I think they should just be removed now.

**Comment by geoffder** [comment]
Fixed by https://github.com/geoffder/clipper2c/pull/3
